# Deliverable 2. Create a Customer Travel Destinations Map.
----
1. Create a folder called `Vacation_Search` to save all the files related with this deliverable.

2. Download the `Vacation_Search_starter_code.ipynb` Jupyter notebook,save it into your `Vacation_Search folder`, and rename it as `Vacation_Search.ipynb`.

3. In the `Vacation_Search.ipynb` file, ensure that the dependencies and the Google API key is imported correctly.

4. From the `Weather_Database` folder you created in the "Deliverable 1," import the `WeatherPy_Database.csv` file as a Pandas DataFrame named `city_data_df`.

5. Write two input statements that prompt the user to enter their minimum and maximum temperature criteria for their vacation.

6. Create a new Pandas DataFrame by using the `loc` Pandas method to filter the `city_data_df` DataFrame for temperature criteria  collected. Name the DataFrame as `preferred_cities_df`.

7. Create a new Pandas DataFrame named `clean_travel_cities` by using the Pandas `dropna` function on the `preferred_cities_df` to drop any empty rows.

8. Use the `copy` Pandas function to create a new DataFrame, called `hotel_df`, by copying the following columns from the `clean_travel_cities` DataFrame: "City", "Country", "Max Temp", "Current Description", "Lat", "Lng".

9. Add a new empty column named `Hotel Name` to the `hotel_df` DataFrame.

10. Review the hotel search parameters provided. These parameters are the same we used in this module; you'll use them to search for a hotel for each city.

11. Use a for loop to iterate through the `hotel_df` DataFrame, retrieve the latitude and longitude of each city to find the nearest hotel based on the search parameters provided, then add the hotel name to the `hotel_df` DataFrame. If a hotel isn't found, skip to the next city.

12. Drop any rows in the `hotel_df` DataFrame where a hotel name is not found and store the resulting data into a new DataFrame named `clean_hotel_df`.

13. Create an CSV file to store the `clean_hotel_df` DataFrame as `WeatherPy_vacation.csv` in the Vacation_Search folder.

14. Review the formatting template provided that you'll use to add an information box to each marker in the map. In the pop-up for each city you'll add:

    1. The city name.

    2. The country code.

    3. The weather description and maximum temperature for the city.

15. Review the provided list comprehension code to retrieve the city data from each row, which will then be added to the formatting template and saved in the `hotel_info` list.

16. Use the provided code snippet to retrieve the latitude and longitude from each row and store them in a new DataFrame called `locations`.

17. Refactor your previous marker layer map code to create a marker layer map that will have pop-up markers for each city on the map.

18. Take a screenshot of your map and save it to the `Vacation_Search` folder as `WeatherPy_vacation_map.png`.
---

## Ensure that the dependencies and the Google API key is imported correctly.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps
# Import Google API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

## From the `Weather_Database` folder you created in the "Deliverable 1," import the `WeatherPy_Database.csv` file as a Pandas DataFrame.

In [2]:
# Set the file path to import the WeatherPy_database.csv file
#file_path = "Weather_Database/WeatherPy_database.csv"
#pd.read_csv("WeatherPy_Database/WeatherPy_database") 

# Load the CSV file into a Pandas DataFrame
city_data_df = pd.read_csv("WeatherPy_Database.csv")

# Display sample data
city_data_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Pierre,US,44.3683,-100.3510,31.86,78,40,9.22,scattered clouds
1,1,Corning,US,42.1428,-77.0547,38.35,78,100,10.36,overcast clouds
2,2,Lexington,US,37.9887,-84.4777,37.98,65,100,8.05,overcast clouds
3,3,Elizabethton,US,36.3487,-82.2107,39.24,71,100,4.61,overcast clouds
4,4,Orange Cove,US,36.6244,-119.3137,68.61,33,0,0.00,haze
5,5,Dodge City,US,37.7528,-100.0171,40.68,42,0,10.36,clear sky
6,6,Indianola,US,41.3581,-93.5574,26.46,70,99,10.00,overcast clouds
7,7,Suffolk,US,40.8668,-72.7996,47.05,73,0,11.50,clear sky
8,8,Eustis,US,28.8528,-81.6853,73.45,82,0,5.75,clear sky
9,9,Ottawa,CA,45.4112,-75.6981,32.88,82,98,1.99,overcast clouds

## Write two input statements that prompt the user to enter their minimum and maximum temperature criteria for their vacation.

In [3]:
# Prompt the user to enter the minimum temperature criteria
min_temp = float(input("What is the minimum temperature you would like for your trip? "))

# Prompt the user to enter the maximum temperature criteria
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 30
What is the maximum temperature you would like for your trip? 90

## Create a new Pandas DataFrame by using the `loc` Pandas method to filter the `city_data_df` DataFrame for temperature criteria  collected.

In [4]:
# Filter the city_data_df DataFrame to find the cities that fit the criteria using the loc Pandas function
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
                                    
# Display sample data
preferred_cities_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Pierre,US,44.3683,-100.3510,31.86,78,40,9.22,scattered clouds
1,1,Corning,US,42.1428,-77.0547,38.35,78,100,10.36,overcast clouds
2,2,Lexington,US,37.9887,-84.4777,37.98,65,100,8.05,overcast clouds
3,3,Elizabethton,US,36.3487,-82.2107,39.24,71,100,4.61,overcast clouds
4,4,Orange Cove,US,36.6244,-119.3137,68.61,33,0,0.00,haze
5,5,Dodge City,US,37.7528,-100.0171,40.68,42,0,10.36,clear sky
7,7,Suffolk,US,40.8668,-72.7996,47.05,73,0,11.50,clear sky
8,8,Eustis,US,28.8528,-81.6853,73.45,82,0,5.75,clear sky
9,9,Ottawa,CA,45.4112,-75.6981,32.88,82,98,1.99,overcast clouds
10,10,Marsh Harbour,BS,26.5412,-77.0636,79.34,74,54,5.68,broken clouds

## Create a new Pandas DataFrame named `clean_travel_cities` by using the Pandas `dropna` function on the `preferred_cities_df` to drop any empty rows.

In [5]:
# Drop any empty rows in the preferred_cities_df DataFrame and create a new DataFrame.
clean_travel_cities = preferred_cities_df.dropna()

# Display sample data
clean_travel_cities.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Pierre,US,44.3683,-100.3510,31.86,78,40,9.22,scattered clouds
1,1,Corning,US,42.1428,-77.0547,38.35,78,100,10.36,overcast clouds
2,2,Lexington,US,37.9887,-84.4777,37.98,65,100,8.05,overcast clouds
3,3,Elizabethton,US,36.3487,-82.2107,39.24,71,100,4.61,overcast clouds
4,4,Orange Cove,US,36.6244,-119.3137,68.61,33,0,0.00,haze
5,5,Dodge City,US,37.7528,-100.0171,40.68,42,0,10.36,clear sky
7,7,Suffolk,US,40.8668,-72.7996,47.05,73,0,11.50,clear sky
8,8,Eustis,US,28.8528,-81.6853,73.45,82,0,5.75,clear sky
9,9,Ottawa,CA,45.4112,-75.6981,32.88,82,98,1.99,overcast clouds
10,10,Marsh Harbour,BS,26.5412,-77.0636,79.34,74,54,5.68,broken clouds

## Use the `copy` Pandas function to create a new DataFrame, called `hotel_df`, by copying the following columns from the `clean_travel_cities` DataFrame: "City", "Country", "Max Temp", "Current Description", "Lat", "Lng".

In [6]:
# Create DataFrame called hotel_df by copying some columns from the clean_travel_cities DataFrame.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Lat", "Lng","Current Description"]].copy()

# Display sample data
hotel_df.head(10)

             City Country  Max Temp      Lat       Lng Current Description
0          Pierre      US     31.86  44.3683 -100.3510    scattered clouds
1         Corning      US     38.35  42.1428  -77.0547     overcast clouds
2       Lexington      US     37.98  37.9887  -84.4777     overcast clouds
3    Elizabethton      US     39.24  36.3487  -82.2107     overcast clouds
4     Orange Cove      US     68.61  36.6244 -119.3137                haze
5      Dodge City      US     40.68  37.7528 -100.0171           clear sky
7         Suffolk      US     47.05  40.8668  -72.7996           clear sky
8          Eustis      US     73.45  28.8528  -81.6853           clear sky
9          Ottawa      CA     32.88  45.4112  -75.6981     overcast clouds
10  Marsh Harbour      BS     79.34  26.5412  -77.0636       broken clouds

## Add a new empty column named `Hotel Name` to the `hotel_df` DataFrame.

In [7]:
# Add a new empty column, "Hotel Name", to the hotel_df DataFrame
hotel_df["Hotel Name"] = ""

# Display sample data

## Review the hotel search parameters provided. These parameters are the same we used in this module; you'll use them to search for a hotel for each city.

In [8]:
# Review the parameters to search for a hotel
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

## Use a for loop to iterate through the `hotel_df` DataFrame, retrieve the latitude and longitude of each city to find the nearest hotel based on the search parameters provided, then add the hotel name to the `hotel_df` DataFrame. If a hotel isn't found, skip to the next city.

In [9]:
# Iterate through the hotel DataFrame 
for index, row in hotel_df.iterrows():
    # Fetch latitude and longitude from the DataFrame
    lat = row["Lat"]
    lng = row["Lng"]
    
    # Add the latitude and longitude as parameters to the params dictionary
    params["location"] = f"{lat},{lng}"
    
    # Set up the base URL for the Google Directions API to get JSON data
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # Make an API request and retrieve the JSON data from the hotel search
    hotels = requests.get(base_url, params=params).json()
    
    # Get the first hotel from the results and store the name, if a hotel isn't found skip the city
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [10]:
# Display sample data

hotel_df.head(10)

,City,Country,Max Temp,Lat,Lng,Current Description,Hotel Name
0,Pierre,US,31.86,44.3683,-100.3510,scattered clouds,Ramkota Hotel
1,Corning,US,38.35,42.1428,-77.0547,overcast clouds,Fairfield Inn Corning Riverside
2,Lexington,US,37.98,37.9887,-84.4777,overcast clouds,DoubleTree Suites by Hilton Hotel Lexington
3,Elizabethton,US,39.24,36.3487,-82.2107,overcast clouds,East Tennessee RV Park
4,Orange Cove,US,68.61,36.6244,-119.3137,haze,
5,Dodge City,US,40.68,37.7528,-100.0171,clear sky,Windsor Inn & Suites
7,Suffolk,US,47.05,40.8668,-72.7996,clear sky,Manorville Estates
8,Eustis,US,73.45,28.8528,-81.6853,clear sky,Quality Inn & Suites Mt Dora North
9,Ottawa,CA,32.88,45.4112,-75.6981,overcast clouds,Delta Hotels by Marriott Ottawa City Centre
10,Marsh Harbour,BS,79.34,26.5412,-77.0636,broken clouds,Abaco Beach Resort

## Drop any rows in the `hotel_df` DataFrame where a hotel name is not found and store the resulting data into a new DataFrame named `clean_hotel_df`.

In [11]:
# Drop the rows where there is no Hotel Name.
clean_hotel_df = hotel_df.dropna()

# Display sample data
clean_hotel_df.head(10)

,City,Country,Max Temp,Lat,Lng,Current Description,Hotel Name
0,Pierre,US,31.86,44.3683,-100.3510,scattered clouds,Ramkota Hotel
1,Corning,US,38.35,42.1428,-77.0547,overcast clouds,Fairfield Inn Corning Riverside
2,Lexington,US,37.98,37.9887,-84.4777,overcast clouds,DoubleTree Suites by Hilton Hotel Lexington
3,Elizabethton,US,39.24,36.3487,-82.2107,overcast clouds,East Tennessee RV Park
4,Orange Cove,US,68.61,36.6244,-119.3137,haze,
5,Dodge City,US,40.68,37.7528,-100.0171,clear sky,Windsor Inn & Suites
7,Suffolk,US,47.05,40.8668,-72.7996,clear sky,Manorville Estates
8,Eustis,US,73.45,28.8528,-81.6853,clear sky,Quality Inn & Suites Mt Dora North
9,Ottawa,CA,32.88,45.4112,-75.6981,overcast clouds,Delta Hotels by Marriott Ottawa City Centre
10,Marsh Harbour,BS,79.34,26.5412,-77.0636,broken clouds,Abaco Beach Resort

**Note:** If the resulting DataFrame is empty, uncomment the following code to load sample data into the `clean_hotel_df`.

## Create an CSV file to store the `clean_hotel_df` DataFrame as `WeatherPy_vacation.csv` in the Vacation_Search folder.

In [12]:
# In case of an empty DataFrame, load the sample data provided
#clean_hotel_df = pd.read_csv("WeatherPy_vacation-backup.csv")
#clean_hotel_df.head(10)

In [13]:
# Set the file name.
output_data_file = "/Users/israelmejia/Desktop/World_Weather_Analysis/Vacation_Search/WeatherPy_vacation.csv"

# Create a CSV file by using the clean_hotel_df DataFrame
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

### Review the formatting template provided that you'll use to add an information box to each marker in the map.

In the pop-up for each city you'll add: 

1. The city name

2. The country code

3. The weather description and maximum temperature for the city

In [14]:
# Review the formatting template provided
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp} °F</dd>
</dl>
"""

## Review the provided list comprehension code to retrieve the city data from each row, which will then be added to the formatting template and saved in the `hotel_info` list.

In [15]:
# Get the data from each row in the clean_hotel_df DataFrame, add it to the formatting template, and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# Display sample data
hotel_info[:10]

['\n<dl>\n<dt>Hotel Name</dt><dd>Ramkota Hotel</dd>\n<dt>City</dt><dd>Pierre</dd>\n<dt>Country</dt><dd>US</dd>\n<dt>Current Weather</dt><dd>scattered clouds and 31.86 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Fairfield Inn Corning Riverside</dd>\n<dt>City</dt><dd>Corning</dd>\n<dt>Country</dt><dd>US</dd>\n<dt>Current Weather</dt><dd>overcast clouds and 38.35 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>DoubleTree Suites by Hilton Hotel Lexington</dd>\n<dt>City</dt><dd>Lexington</dd>\n<dt>Country</dt><dd>US</dd>\n<dt>Current Weather</dt><dd>overcast clouds and 37.98 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>East Tennessee RV Park</dd>\n<dt>City</dt><dd>Elizabethton</dd>\n<dt>Country</dt><dd>US</dd>\n<dt>Current Weather</dt><dd>overcast clouds and 39.24 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd></dd>\n<dt>City</dt><dd>Orange Cove</dd>\n<dt>Country</dt><dd>US</dd>\n<dt>Current Weather</dt><dd>haze and 68.61 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Windsor Inn & Suites</dd>\n<dt>City</dt><dd>Dodge City</dd>\n<dt>Country</dt><dd>US</dd>\n<dt>Current Weather</dt><dd>clear sky and 40.68 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Manorville Estates</dd>\n<dt>City</dt><dd>Suffolk</dd>\n<dt>Country</dt><dd>US</dd>\n<dt>Current Weather</dt><dd>clear sky and 47.05 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Quality Inn & Suites Mt Dora North</dd>\n<dt>City</dt><dd>Eustis</dd>\n<dt>Country</dt><dd>US</dd>\n<dt>Current Weather</dt><dd>clear sky and 73.45 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Delta Hotels by Marriott Ottawa City Centre</dd>\n<dt>City</dt><dd>Ottawa</dd>\n<dt>Country</dt><dd>CA</dd>\n<dt>Current Weather</dt><dd>overcast clouds and 32.88 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Abaco Beach Resort</dd>\n<dt>City</dt><dd>Marsh Harbour</dd>\n<dt>Country</dt><dd>BS</dd>\n<dt>Current Weather</dt><dd>broken clouds and 79.34 °F</dd>\n</dl>\n']

## Use the provided code snippet to retrieve the latitude and longitude from each row and store them in a new DataFrame called `locations`.

In [16]:
# Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

# Display sample data
locations.head(10)

        Lat       Lng
0   44.3683 -100.3510
1   42.1428  -77.0547
2   37.9887  -84.4777
3   36.3487  -82.2107
4   36.6244 -119.3137
5   37.7528 -100.0171
7   40.8668  -72.7996
8   28.8528  -81.6853
9   45.4112  -75.6981
10  26.5412  -77.0636

## Refactor your previous marker layer map code to create a marker layer map that will have pop-up markers for each city on the map.

In [18]:
# Add a marker layer for each city to the map. 
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)

# Create a figure to add the Google map as a layer
fig = gmaps.figure()
fig.add_layer(marker_layer)

# Display the figure containing the map
fig

Figure(layout=FigureLayout(height='420px'))